# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RdsAuthProxy < Formula
  desc "The rds-auth-proxy client command lets you aws iam auth for postgres compatible rds instances."
  homepage "https://github.com/JacobJohansen/rds-auth-proxy"
  version "0.2.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JacobJohansen/rds-auth-proxy/releases/download/v0.2.15/rds-auth-proxy_0.2.15_darwin_arm64.tar.gz"
      sha256 "31fe68fdc50ddf8aaf09badd65074a2f6eb784cf73aeb9b961f748344f6213e0"

      def install
        bin.install "rds-auth-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JacobJohansen/rds-auth-proxy/releases/download/v0.2.15/rds-auth-proxy_0.2.15_darwin_amd64.tar.gz"
      sha256 "c039a80a514aff3c7e5964c07273f7f2723c48db177e392fac5a0492a827ac39"

      def install
        bin.install "rds-auth-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/JacobJohansen/rds-auth-proxy/releases/download/v0.2.15/rds-auth-proxy_0.2.15_linux_armv6.tar.gz"
      sha256 "92def94041320f80d61fd48081acb235f0f32128f573ddffedcf7234422a6441"

      def install
        bin.install "rds-auth-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JacobJohansen/rds-auth-proxy/releases/download/v0.2.15/rds-auth-proxy_0.2.15_linux_arm64.tar.gz"
      sha256 "7ac6763960ea4c841fe9b5f37589dfaae9a23346d3fe219b41bdb56ed6235897"

      def install
        bin.install "rds-auth-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JacobJohansen/rds-auth-proxy/releases/download/v0.2.15/rds-auth-proxy_0.2.15_linux_amd64.tar.gz"
      sha256 "132689a9aedbfd3ec8bca4d3b7e8c2c7e32ac0ba0d889cb2e537b9058209fc23"

      def install
        bin.install "rds-auth-proxy"
      end
    end
  end

  def caveats
    <<~EOS
      Type 'rds-auth-proxy client' on your command line and let it handle aws rds iam authentication. This command currently only tested on macOS and Linux
    EOS
  end

  test do
    system "#{bin}/rds-auth-proxy --version"
  end
end
